### ISSUE TITLE
Create Sign up page component

### ISSUE THREAD

**Issue by christine-aqui** [LACE-Team/lace-repo#31]

**Comment by christine-aqui** [comment]
Example of Signup page concept.

login is a component
sign up is a component

![image](https://user-images.githubusercontent.com/2739361/45604625-28168480-ba04-11e8-81c0-49157c6459fd.png)

Note: its possible we can have one component for the login and sigin up and depending on the route have conditional functions on it for login and signup...

**Comment by k4meli4** [comment]
Collecting for Sign Up:
Name
DOB
Postal Code
Organization
Username
Password

**Comment by christine-aqui** [comment]
not needed
